### ISSUE TITLE
Issue with ModifiedProperties while updating

### ISSUE THREAD

**Issue by oliviermalea** [TrackableEntities/trackable-entities#103]
Hi Tony, I'm working on a WCF service bound by Rest to an api.

Rest layer has its own generated methods (PUT, GET, …), it doesn’t use your T.E. helpers.

Protobuf is used for serialization.

I’m using T.E., it works like a charm most of times (many thanks for your work !), but when it comes to updating one or few properties, an issue occurs with “ModifiedProperties”( ICollection) .

The method ignitiating Update looks like this :

        public DTOService TestUpdate()
        {
            DTOService res = DtoserviceClient.GetDtoservice(client, Currentuser.Id);
            var changeTracker = new ChangeTrackingCollection<DTOService>(res);
            string modifiedName = "TESTSERVICE";
            res.Name = modifiedName;
            var changed = changeTracker.GetChanges().SingleOrDefault();
            // update
            res = DtoserviceClient.UpdateDtoservice(client, changed );
            changeTracker.MergeChanges(res);
            return res;
        }

I just try to modified “Name” value.

At this point,  the Update method transmits an entity containing ModifiedProperties (and by the way our modified “Name” property).
The value is conform.

Finally, the put method :

       // PUT api/DTOService (UPDATE)
       public HttpResponseMessage PutDtoservice(DTOService entity)
       {    //part of code removed
             try
             {       
                    _dbContext.ApplyChanges(entity); // This step triggers an exception    
                    try
                    {
                           _dbContext.SaveChanges();   
                    } //part of code removed
             return response;
       }

It’s the point of trouble : ModifiedProperties received inside Put method display an incoherent value, formatted with cabalistic signs instead of coherent text… 

Exception details :
2016-01-12 15:48:11,594 [11] [(null)] AppointmentController ERROR System.ArgumentException: The property 'RName' on type 'DTOService' is not a primitive or complex property. The Property method can only be used with primitive or complex properties. Use the Reference or Collection method.
   at System.Data.Entity.Internal.InternalEntityEntry.Property(InternalPropertyEntry parentProperty, String propertyName, IList`1 properties, Type requestedType, Boolean requireComplex)
   at System.Data.Entity.Internal.InternalEntityEntry.Property(String property, Type requestedType, Boolean requireComplex)
   at System.Data.Entity.Infrastructure.DbEntityEntry`1.Property(String propertyName)
   at TrackableEntities.EF5.DbContextExtensions.ApplyChanges(DbContext context, ITrackable item, ITrackable parent, ObjectVisitationHelper visitationHelper, String propertyName, Nullable`1 state)
   at TrackableEntities.EF5.DbContextExtensions.ApplyChanges(DbContext context, ITrackable item)
   at Accel.Planning.Data.Server.WebApi.Controllers.DtoserviceController.PutDtoservice(DTOService entity) in d:\ ...

Do you have any clue about that issue ?

Thanks by advance !

**Comment by tonysneed** [comment]
It looks like a protobuf issue. How are you configuring your web api to use protobuf?

**Comment by oliviermalea** [comment]
Tony,

First of all thanks for your answer, i have this in mind, and you confirmed my first idea.

The ICollection ModifiedProperties had the following decoration (template version) =

[DataMember(Order = <#=order #>)]
[ProtoMember(<#=order++ #>, AsReference = true)]
public ICollection<string> ModifiedProperties { get; set; }

What I did was simply to suppress "AsReference = true" parameter, regenerating the templates and it finally works.

Thanks for your support, i close the topic.

**Comment by tonysneed** [comment]
Glad you worked it out! :smile:
